---
#  Executes Powershell scripts remotely
#  via HTTP API for remote Windows PC
#  control.
#
#  https://blogs.msdn.microsoft.com/powershell/2014/09/29/simple-http-api-for-executing-powershell-scripts/

- platform: command_line
  switches:
    sound:
      oncmd: !env_var PC_SOUND_TOGGLE
      offcmd: !env_var PC_SOUND_TOGGLE
      initial: 'on'
    monitors:
      oncmd: !env_var PC_MONITORS_ON
      offcmd: !env_var PC_MONITORS_OFF
      initial: 'on'
