---
#  Monitor his and hers morning and evening commute times.
#  Useful for automations and notifications.

- platform: google_travel_time
  name: His Morning
  api_key: !env_var GOOGLE_API_KEY
  origin: !env_var HOME_ADDRESS
  destination: !env_var HIS_WORK_ADDRESS
  options:
    mode: driving

- platform: google_travel_time
  name: His Evening
  api_key: !env_var GOOGLE_API_KEY
  origin: !env_var HIS_WORK_ADDRESS
  destination: !env_var HOME_ADDRESS
  options:
    mode: driving
