---
alias: Commute delay - his evening
trigger:
  platform: numeric_state
  entity_id: sensor.his_evening
  above: 25
condition:
  - condition: time
    after: '15:00:00'
    before: '16:30:00'
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  - condition: state
    entity_id: switch.alert_delays
    state: 'on'
  - condition: state
    entity_id: device_tracker.his_phone
    state: 'not_home'
action:
  service: notify.notify
  data_template:
    message: >
      Commute delay of {{ trigger.to_state.state|round }} minutes
