---
#  Several other processes run on the home server.
#  Get alerted if any of them go down.

alias: Process down
trigger:
  platform: state
  from: 'RUNNING'
  entity_id:
  #- sensor.mosquitto
condition:
- condition: template
  value_template: '{{ trigger.to_state.state != "RUNNING" }}'
action:
  service: notify.notify
  data_template:
    message: >
      {{ trigger.entity_id.split('.')[1] }} is {{ trigger.to_state.state.lower() }}
